package tlscert

import (
	"crypto/ecdsa"
	"crypto/elliptic"
	"crypto/rand"
	"crypto/sha1"
	"crypto/tls"
	"crypto/x509"
	"crypto/x509/pkix"
	"encoding/pem"
	"fmt"
	"math/big"
	"os"
	"path/filepath"
	"time"
)

const (
	caKeyFile  = "ca.key"
	caCertFile = "ca.crt"
	wcKeyFile  = "wildcard.key"
	wcCertFile = "wildcard.crt"
)

// EnsureCert generates a local CA + wildcard cert for *.tunnel.test if not already
// present, if the existing cert lacks Authority Key Identifier (old format), or if
// the cert SANs don't match the current TLD.
// Stores PEM files in dataDir. Returns the loaded cert and path to the CA cert.
func EnsureCert(dataDir string) (*tls.Certificate, string, error) {
	if err := os.MkdirAll(dataDir, 0700); err != nil {
		return nil, "", err
	}

	caFile := filepath.Join(dataDir, caCertFile)

	if cert, err := LoadCert(dataDir); err == nil {
		return cert, caFile, nil
	}

	// Generate CA key + cert
	caKey, err := ecdsa.GenerateKey(elliptic.P256(), rand.Reader)
	if err != nil {
		return nil, "", fmt.Errorf("generating CA key: %w", err)
	}
	caKeyID := pubKeyID(&caKey.PublicKey)

	caTemplate := &x509.Certificate{
		SerialNumber:          mustRandSerial(),
		Subject:               pkix.Name{CommonName: "local-auto-domain CA"},
		NotBefore:             time.Now().Add(-time.Minute),
		NotAfter:              time.Now().Add(10 * 365 * 24 * time.Hour),
		KeyUsage:              x509.KeyUsageCertSign | x509.KeyUsageCRLSign,
		BasicConstraintsValid: true,
		IsCA:                  true,
		SubjectKeyId:          caKeyID,
	}

	caCertDER, err := x509.CreateCertificate(rand.Reader, caTemplate, caTemplate, &caKey.PublicKey, caKey)
	if err != nil {
		return nil, "", fmt.Errorf("creating CA cert: %w", err)
	}

	caCert, err := x509.ParseCertificate(caCertDER)
	if err != nil {
		return nil, "", err
	}

	// Generate wildcard key + cert
	wcKey, err := ecdsa.GenerateKey(elliptic.P256(), rand.Reader)
	if err != nil {
		return nil, "", fmt.Errorf("generating wildcard key: %w", err)
	}

	wcTemplate := &x509.Certificate{
		SerialNumber:   mustRandSerial(),
		Subject:        pkix.Name{CommonName: "*.tunnel.test"},
		DNSNames:       []string{"*.tunnel.test", "tunnel.test"},
		NotBefore:      time.Now().Add(-time.Minute),
		NotAfter:       time.Now().Add(2 * 365 * 24 * time.Hour),
		KeyUsage:       x509.KeyUsageDigitalSignature,
		ExtKeyUsage:    []x509.ExtKeyUsage{x509.ExtKeyUsageServerAuth},
		SubjectKeyId:   pubKeyID(&wcKey.PublicKey),
		AuthorityKeyId: caKeyID,
	}

	wcCertDER, err := x509.CreateCertificate(rand.Reader, wcTemplate, caCert, &wcKey.PublicKey, caKey)
	if err != nil {
		return nil, "", fmt.Errorf("creating wildcard cert: %w", err)
	}

	// Write all four PEM files
	if err := writeCertPEM(caFile, caCertDER); err != nil {
		return nil, "", err
	}
	if err := writeKeyPEM(filepath.Join(dataDir, caKeyFile), caKey); err != nil {
		return nil, "", err
	}
	wcCertPath := filepath.Join(dataDir, wcCertFile)
	if err := writeCertPEM(wcCertPath, wcCertDER); err != nil {
		return nil, "", err
	}
	if err := writeKeyPEM(filepath.Join(dataDir, wcKeyFile), wcKey); err != nil {
		return nil, "", err
	}

	// Build tls.Certificate with full chain: leaf + CA
	cert := tls.Certificate{
		Certificate: [][]byte{wcCertDER, caCertDER},
		PrivateKey:  wcKey,
		Leaf:        caCert, // will be overwritten below
	}
	leaf, _ := x509.ParseCertificate(wcCertDER)
	cert.Leaf = leaf

	return &cert, caFile, nil
}

// LoadCert loads the wildcard cert from dataDir without generating anything.
// Returns an error if certs are missing, expiring within 30 days, or were
// generated without AuthorityKeyId (old format — triggers regeneration).
func LoadCert(dataDir string) (*tls.Certificate, error) {
	wcCertPath := filepath.Join(dataDir, wcCertFile)
	wcKeyPath := filepath.Join(dataDir, wcKeyFile)
	caCertPath := filepath.Join(dataDir, caCertFile)

	certPEM, err := os.ReadFile(wcCertPath)
	if err != nil {
		return nil, err
	}
	keyPEM, err := os.ReadFile(wcKeyPath)
	if err != nil {
		return nil, err
	}
	caPEM, err := os.ReadFile(caCertPath)
	if err != nil {
		return nil, err
	}

	tlsCert, err := tls.X509KeyPair(certPEM, keyPEM)
	if err != nil {
		return nil, err
	}

	leaf, err := x509.ParseCertificate(tlsCert.Certificate[0])
	if err != nil {
		return nil, err
	}
	if time.Now().After(leaf.NotAfter.Add(-30 * 24 * time.Hour)) {
		return nil, fmt.Errorf("cert expires %s", leaf.NotAfter.Format("2006-01-02"))
	}
	// Regenerate if cert lacks AuthorityKeyId (generated by older code without SKI/AKI)
	if len(leaf.AuthorityKeyId) == 0 {
		return nil, fmt.Errorf("cert missing AuthorityKeyId — regenerating")
	}
	// Regenerate if cert SANs don't match the current TLD (e.g. old *.tunnel.localhost certs)
	hasTunnelTest := false
	for _, san := range leaf.DNSNames {
		if san == "*.tunnel.test" {
			hasTunnelTest = true
			break
		}
	}
	if !hasTunnelTest {
		return nil, fmt.Errorf("cert SANs don't include *.tunnel.test — regenerating")
	}

	// Parse CA cert and append its DER to the chain
	caBlock, _ := pem.Decode(caPEM)
	if caBlock == nil {
		return nil, fmt.Errorf("invalid CA cert PEM")
	}
	tlsCert.Certificate = append(tlsCert.Certificate, caBlock.Bytes)
	tlsCert.Leaf = leaf

	return &tlsCert, nil
}

// pubKeyID returns the SHA-1 hash of the DER-encoded public key (RFC 5280 §4.2.1.2).
func pubKeyID(pub *ecdsa.PublicKey) []byte {
	der, _ := x509.MarshalPKIXPublicKey(pub)
	sum := sha1.Sum(der) //nolint:gosec // SHA-1 used only as identifier, not for security
	return sum[:]
}

func mustRandSerial() *big.Int {
	n, err := rand.Int(rand.Reader, new(big.Int).Lsh(big.NewInt(1), 128))
	if err != nil {
		panic(err)
	}
	return n
}

func writeCertPEM(path string, der []byte) error {
	f, err := os.OpenFile(path, os.O_CREATE|os.O_WRONLY|os.O_TRUNC, 0600)
	if err != nil {
		return err
	}
	defer f.Close()
	return pem.Encode(f, &pem.Block{Type: "CERTIFICATE", Bytes: der})
}

func writeKeyPEM(path string, key *ecdsa.PrivateKey) error {
	der, err := x509.MarshalECPrivateKey(key)
	if err != nil {
		return err
	}
	f, err := os.OpenFile(path, os.O_CREATE|os.O_WRONLY|os.O_TRUNC, 0600)
	if err != nil {
		return err
	}
	defer f.Close()
	return pem.Encode(f, &pem.Block{Type: "EC PRIVATE KEY", Bytes: der})
}
